version: 0.2

run-as: root

env:
  variables:
    environment: "dev"
            
phases:
  install:
    run-as: root
    runtime-versions:
      java: corretto8
    commands:
      - echo 'install'
  build:
    run-as: root
    commands:
      - ./gradlew compileJava 
  